### PR TITLE
Fix issue with C++ endf float converter

### LINKED ISSUE #6: Silent crash in float_endf
Hi,

Firstly, thanks for this tool - I am working on using it in my project NeSST (https://github.com/aidancrilly/NeSST).

I just wanted to document this issue I had. Some details, this occurred on a Windows machine, installed without error using pip and MSVC 2022. I could import the library but loading any endf file would silently crash. I suspected this was the pybind'ed C++ so I swapped from using float_endf from the C++ to the py_float_endf. The code then ran without crashing.

Is there a reason to use the C++ version over the python version?

### PR DESCRIPTION
**Pull request by aidancrilly**
This closes #6 - at least for me, I noticed someone having similar issues in #4.

The crash seems to be a seg fault that occurs when the endf float being converted is negative, i.e. has a leading minus sign.

Positive numbers have leading whitespace so hit the continue statement and j is not incremented. Therefore, the first digit is placed at arr[0]. However, negative numbers had the leading minus sign placed at arr[0] and first digit at arr[1]. This means when the null terminator is placed at the end, for negative numbers this is at arr[12] so the crash occurs.

EDIT: my initial commit was not the correct solution, I think it is simply a case of increasing arr to be length 13 so it has space for both the e and null terminator if the input buffer is length 11. Apologies, some how my initial incorrect fix ran (I have no idea how!) but on restarting it failed. 

This would seem to me to be an issue across systems.

### CODE REVIEW

**Comment by aidancrilly** [comment]
@paulromano 
Sure, in ENDF/B-VIII.0 incident neutron data for deuterium there is -2.225002+6 at the beginning of the MF = 3, MT = 16 record. This is the QM/QI value.

File: src/endf/_records.cpp [hunk 1]
```diff
@@ -25,11 +25,12 @@ double cfloat_endf(const char* buffer)
   int n = std::strlen(buffer);
 
   int i;
+
   for (i = 0; i < n; ++i) {
     char c = buffer[i];
 
     // Skip whitespace characters
-    if (c == ' ') continue;
+    if (std::isspace(c)) continue;
```
Comment (paulromano) [inline src/endf/_records.cpp:33]: The ENDF format actually does not allow characters like `\t` and `\f` which are handled by `std::isspace`. Sticking with the original check against a space should be sufficient.

**Review by paulromano — CHANGES_REQUESTED** [review]
Thanks again! Just one small request:

**Review by paulromano — APPROVED** [review]

**Comment by paulromano** [comment]
@aidancrilly Would you be up for making a similar PR to [OpenMC](https://github.com/openmc-dev/openmc)? The `cfloat_endf` function was originally borrowed from there:
https://github.com/openmc-dev/openmc/blob/develop/openmc/data/endf.c

It would be good to also add the example you mentioned (-2.225002+6) to the tests here:
https://github.com/openmc-dev/openmc/blob/develop/tests/unit_tests/test_endf.py
